//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("OnStage.Entities", "ShowMasterCueBook", "Show", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnStage.Entities.Show), "MasterCueBook", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnStage.Entities.MasterCueBook))]
[assembly: EdmRelationshipAttribute("OnStage.Entities", "ShowCueBook", "Show", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnStage.Entities.Show), "CueBook", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnStage.Entities.CueBook))]
[assembly: EdmRelationshipAttribute("OnStage.Entities", "CueBookCue", "CueBook", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnStage.Entities.CueBook), "Cue", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnStage.Entities.Cue))]
[assembly: EdmRelationshipAttribute("OnStage.Entities", "MasterCueBookMasterCue", "MasterCueBook", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnStage.Entities.MasterCueBook), "MasterCue", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnStage.Entities.MasterCue))]
[assembly: EdmRelationshipAttribute("OnStage.Entities", "MasterCueCue", "MasterCue", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnStage.Entities.MasterCue), "Cue", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnStage.Entities.Cue))]

#endregion

namespace OnStage.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OnStageEntitiesContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OnStageEntitiesContainer object using the connection string found in the 'OnStageEntitiesContainer' section of the application configuration file.
        /// </summary>
        public OnStageEntitiesContainer() : base("name=OnStageEntitiesContainer", "OnStageEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OnStageEntitiesContainer object.
        /// </summary>
        public OnStageEntitiesContainer(string connectionString) : base(connectionString, "OnStageEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OnStageEntitiesContainer object.
        /// </summary>
        public OnStageEntitiesContainer(EntityConnection connection) : base(connection, "OnStageEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Show> Shows
        {
            get
            {
                if ((_Shows == null))
                {
                    _Shows = base.CreateObjectSet<Show>("Shows");
                }
                return _Shows;
            }
        }
        private ObjectSet<Show> _Shows;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MasterCueBook> MasterCueBooks
        {
            get
            {
                if ((_MasterCueBooks == null))
                {
                    _MasterCueBooks = base.CreateObjectSet<MasterCueBook>("MasterCueBooks");
                }
                return _MasterCueBooks;
            }
        }
        private ObjectSet<MasterCueBook> _MasterCueBooks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CueBook> CueBooks
        {
            get
            {
                if ((_CueBooks == null))
                {
                    _CueBooks = base.CreateObjectSet<CueBook>("CueBooks");
                }
                return _CueBooks;
            }
        }
        private ObjectSet<CueBook> _CueBooks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MasterCue> MasterCues
        {
            get
            {
                if ((_MasterCues == null))
                {
                    _MasterCues = base.CreateObjectSet<MasterCue>("MasterCues");
                }
                return _MasterCues;
            }
        }
        private ObjectSet<MasterCue> _MasterCues;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cue> Cues
        {
            get
            {
                if ((_Cues == null))
                {
                    _Cues = base.CreateObjectSet<Cue>("Cues");
                }
                return _Cues;
            }
        }
        private ObjectSet<Cue> _Cues;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Shows EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShows(Show show)
        {
            base.AddObject("Shows", show);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MasterCueBooks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMasterCueBooks(MasterCueBook masterCueBook)
        {
            base.AddObject("MasterCueBooks", masterCueBook);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CueBooks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCueBooks(CueBook cueBook)
        {
            base.AddObject("CueBooks", cueBook);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MasterCues EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMasterCues(MasterCue masterCue)
        {
            base.AddObject("MasterCues", masterCue);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cues EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCues(Cue cue)
        {
            base.AddObject("Cues", cue);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OnStage.Entities", Name="Cue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cue object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Cue CreateCue(global::System.Int32 id)
        {
            Cue cue = new Cue();
            cue.Id = id;
            return cue;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnStage.Entities", "CueBookCue", "CueBook")]
        public CueBook CueBook
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CueBook>("OnStage.Entities.CueBookCue", "CueBook").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CueBook>("OnStage.Entities.CueBookCue", "CueBook").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CueBook> CueBookReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CueBook>("OnStage.Entities.CueBookCue", "CueBook");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CueBook>("OnStage.Entities.CueBookCue", "CueBook", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OnStage.Entities", Name="CueBook")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CueBook : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CueBook object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static CueBook CreateCueBook(global::System.Int32 id)
        {
            CueBook cueBook = new CueBook();
            cueBook.Id = id;
            return cueBook;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnStage.Entities", "ShowCueBook", "Show")]
        public Show Show
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Show>("OnStage.Entities.ShowCueBook", "Show").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Show>("OnStage.Entities.ShowCueBook", "Show").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Show> ShowReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Show>("OnStage.Entities.ShowCueBook", "Show");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Show>("OnStage.Entities.ShowCueBook", "Show", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnStage.Entities", "CueBookCue", "Cue")]
        public EntityCollection<Cue> Cues
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cue>("OnStage.Entities.CueBookCue", "Cue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cue>("OnStage.Entities.CueBookCue", "Cue", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OnStage.Entities", Name="MasterCue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MasterCue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MasterCue object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static MasterCue CreateMasterCue(global::System.Int32 id)
        {
            MasterCue masterCue = new MasterCue();
            masterCue.Id = id;
            return masterCue;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnStage.Entities", "MasterCueBookMasterCue", "MasterCueBook")]
        public MasterCueBook MasterCueBook
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MasterCueBook>("OnStage.Entities.MasterCueBookMasterCue", "MasterCueBook").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MasterCueBook>("OnStage.Entities.MasterCueBookMasterCue", "MasterCueBook").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MasterCueBook> MasterCueBookReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MasterCueBook>("OnStage.Entities.MasterCueBookMasterCue", "MasterCueBook");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MasterCueBook>("OnStage.Entities.MasterCueBookMasterCue", "MasterCueBook", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnStage.Entities", "MasterCueCue", "Cue")]
        public EntityCollection<Cue> SubCues
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cue>("OnStage.Entities.MasterCueCue", "Cue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cue>("OnStage.Entities.MasterCueCue", "Cue", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OnStage.Entities", Name="MasterCueBook")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MasterCueBook : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MasterCueBook object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static MasterCueBook CreateMasterCueBook(global::System.Int32 id)
        {
            MasterCueBook masterCueBook = new MasterCueBook();
            masterCueBook.Id = id;
            return masterCueBook;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnStage.Entities", "ShowMasterCueBook", "Show")]
        public Show Show
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Show>("OnStage.Entities.ShowMasterCueBook", "Show").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Show>("OnStage.Entities.ShowMasterCueBook", "Show").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Show> ShowReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Show>("OnStage.Entities.ShowMasterCueBook", "Show");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Show>("OnStage.Entities.ShowMasterCueBook", "Show", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnStage.Entities", "MasterCueBookMasterCue", "MasterCue")]
        public EntityCollection<MasterCue> Cues
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MasterCue>("OnStage.Entities.MasterCueBookMasterCue", "MasterCue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MasterCue>("OnStage.Entities.MasterCueBookMasterCue", "MasterCue", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OnStage.Entities", Name="Show")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Show : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Show object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Show CreateShow(global::System.Int32 id)
        {
            Show show = new Show();
            show.Id = id;
            return show;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnStage.Entities", "ShowMasterCueBook", "MasterCueBook")]
        public MasterCueBook MasterCueBook
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MasterCueBook>("OnStage.Entities.ShowMasterCueBook", "MasterCueBook").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MasterCueBook>("OnStage.Entities.ShowMasterCueBook", "MasterCueBook").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MasterCueBook> MasterCueBookReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MasterCueBook>("OnStage.Entities.ShowMasterCueBook", "MasterCueBook");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MasterCueBook>("OnStage.Entities.ShowMasterCueBook", "MasterCueBook", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnStage.Entities", "ShowCueBook", "CueBook")]
        public EntityCollection<CueBook> CueBooks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CueBook>("OnStage.Entities.ShowCueBook", "CueBook");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CueBook>("OnStage.Entities.ShowCueBook", "CueBook", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
